#!/usr/bin/env python3
import argparse, bisect, os, re, subprocess
from pathlib import Path

ROOT_MARKERS = ("kernel/", "drivers/", "includes/")

def q(s):
    return '"' + s.replace('\\','\\\\').replace('"','\\"').replace('\t','    ').rstrip('\n') + '"'

def rel(path, root):
    if not path or path == '??': return None
    p = Path(path)
    try: return p.resolve().relative_to(root.resolve()).as_posix()
    except Exception:
        s = path.replace('\\','/')
        for m in ROOT_MARKERS:
            i=s.find(m)
            if i>=0: return s[i:]
    return None

def load_lines(file, line, root, ctx=3):
    rp = rel(file, root)
    if not rp: return []
    path = root / rp
    try: lines = path.read_text(errors='replace').splitlines()
    except Exception: return []
    start=max(1,line-ctx); end=min(len(lines), line+ctx)
    return [(n, lines[n-1][:160]) for n in range(start,end+1)]

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--kernel', required=True); ap.add_argument('--root', required=True); ap.add_argument('--out', required=True)
    a=ap.parse_args(); root=Path(a.root)
    nm=subprocess.check_output(['nm','-n',a.kernel], text=True, errors='replace')
    funcs=[]
    for line in nm.splitlines():
        parts=line.split()
        if len(parts)>=3 and parts[1].lower()=='t': funcs.append((int(parts[0],16), parts[2]))
    addrs=[x[0] for x in funcs]
    entries=[]; snippets={}; snip_names={}
    # Prefer DWARF decoded line rows so a saved RIP resolves to the exact C line,
    # not merely the function entry line.  Each row covers [address,next_address).
    decoded = subprocess.check_output(['objdump','--dwarf=decodedline',a.kernel], text=True, errors='replace')
    rows=[]; current_file=None
    row_re=re.compile(r'^(.+?)\s+(\d+)\s+(0x[0-9a-fA-F]+)')
    for raw in decoded.splitlines():
        line=raw.rstrip()
        if line.endswith(':') and not line.startswith('Contents') and not line.startswith(a.kernel):
            current_file=line[:-1]
            continue
        m=row_re.match(line.strip())
        if not m: continue
        file_name, line_s, addr_s = m.groups()
        try:
            lno=int(line_s); addr=int(addr_s,16)
        except Exception:
            continue
        if lno<=0: continue
        rp=rel(file_name, root) or rel(current_file, root)
        if not rp and current_file:
            matches=list(root.rglob(current_file))
            if matches: rp=matches[0].relative_to(root).as_posix()
        if not rp: continue
        rows.append((addr,rp,lno))
    rows=sorted(set(rows))
    for i,(addr,rp,lno) in enumerate(rows):
        end_addr=rows[i+1][0] if i+1<len(rows) else addr+1
        if end_addr <= addr: continue
        idx=bisect.bisect_right(addrs, addr)-1
        func=funcs[idx][1] if idx>=0 else 'unknown'
        snip=load_lines(str(root/rp),lno,root)
        key=(rp,lno,tuple(snip))
        if key not in snip_names:
            snip_names[key]=f'snippet_{len(snip_names)}'
            snippets[snip_names[key]]=snip
        entries.append((addr,end_addr,func,rp,lno,snip_names[key],len(snip)))

    # If DWARF line decoding produced nothing, fall back to one entry per text
    # symbol.  The panic screen will still make clear when only limited mapping
    # exists instead of inventing data.
    if not entries:
        for i,(start,name) in enumerate(funcs):
            if name.startswith(('isr_stub_','irq_stub_')): continue
            end=funcs[i+1][0] if i+1<len(funcs) else start+1
            try:
                out=subprocess.check_output(['addr2line','-e',a.kernel,'-f','-C',hex(start)], text=True, errors='replace').splitlines()
            except Exception: continue
            func=out[0].strip() if out else name
            loc=out[1].strip() if len(out)>1 else '??:0'
            if loc.startswith('??'): continue
            filepart, _, linepart = loc.rpartition(':')
            try: lno=int(linepart.split()[0])
            except Exception: continue
            rp=rel(filepart, root)
            if not rp or lno<=0: continue
            snip=load_lines(filepart,lno,root)
            key=(rp,lno,tuple(snip))
            if key not in snip_names:
                snip_names[key]=f'snippet_{len(snip_names)}'
                snippets[snip_names[key]]=snip
            entries.append((start,end,func,rp,lno,snip_names[key],len(snip)))
    with open(a.out,'w') as f:
        f.write('/* Generated by scripts/gen_crash_symbols.py. */\n#include <crash_symbols.h>\n\n')
        for name,snip in snippets.items():
            f.write(f'static const CrashSourceLine {name}[] = {{\n')
            for n,t in snip: f.write(f'    {{{n}, {q(t)}}},\n')
            f.write('};\n')
        f.write('const CrashSymbol wing_crash_symbols[] = {\n')
        for st,en,fn,rp,lno,sn,ct in entries:
            f.write(f'    {{0x{st:x}ULL, 0x{en:x}ULL, {q(fn)}, {q(rp)}, {lno}, {sn}, {ct}}},\n')
        f.write('};\n')
        f.write(f'const uint32 wing_crash_symbol_count = {len(entries)};\n')
if __name__=='__main__': main()
