name: Frosted Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: FrostWing
    steps:
    - uses: actions/checkout@v1
    - name: Update packages
      run: sudo apt update

    - name: Install other dependencies
      run: sudo apt install -y make bison flex texinfo nasm mtools wget tar binutils build-essential doxygen git jq curl qemu-system-x86 novnc imagemagick x11vnc
    
    - name: Build Doxygen Documentations
      run: doxygen

    - name: Obtain the Limine Bootloader
      run: git clone https://github.com/limine-bootloader/limine.git --branch=v5.x-branch-binary --depth=1

    - name: Build the Limine Bootloader
      run: make -C limine

    - name: Build The Operating System itself
      run: cd source && ./versions.sh && make -j4 clean && cd ../ && make -j4 -C source && make -j4

    - name: Run the QEMU Emulator
      run: |
        sudo x11vnc -display :1 -rfbport 5900 -noxdamage -forever -bg
        make run-x86-vnc
    
    - name: Waiting for the QEMU to start
      run: sleep 5s

    - name: Capturing Screenshot
      run: |
        vncviewer -encodings "tight" -compresslevel 9 -quality 0 localhost:5900 -fullscreen -grabpng - | convert - screenshot.png

    - name: Stop QEMU and VNC
      run: |
        sudo pkill qemu
        sudo pkill x11vnc
  
    - name: Upload to file.io
      run: ls && curl -F "file=@./FrostWing.iso"  https://file.io | jq && curl -F "file=@./screenshot.png"  https://file.io | jq
