name: Frosted Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: FrostWing
    steps:
    - uses: actions/checkout@v1
    - name: Update packages
      run: sudo apt update

    - name: Install other dependencies
      run: sudo apt install -y make bison flex texinfo nasm mtools wget tar binutils build-essential doxygen git jq curl qemu-system-x86  
    
    - name: Build Doxygen Documentations
      run: doxygen

    - name: Obtain the Limine Bootloader
      run: git clone https://github.com/limine-bootloader/limine.git --branch=v6.x-branch-binary --depth=1

    - name: Build the Limine Bootloader
      run: make -C limine

    - name: Build The Operating System itself
      run: cd source && ./versions.sh && make -j4 clean && cd ../ && make -j4 -C source && make -j4

    - name: Run the QEMU Emulator
      run: make run-x86-vnc
    
    - name: Waiting for the QEMU to start
      run: sleep 5s

    - name: Stop QEMU and VNC
      run: sudo pkill qemu
  
    - name: Upload to file.io
      run: ls && curl -F "file=@./FrostWing.iso"  https://file.io
