name: Frosted Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: FrostWing
    steps:
    - uses: actions/checkout@v1
    - name: Update packages
      run: sudo apt update

    - name: Install other dependencies
      run: sudo apt install -y make bison flex texinfo nasm mtools wget tar binutils build-essential doxygen git
    
    - name: Build Doxygen Documentations
      run: doxygen

    - name: Obtain the Limine Bootloader
      run: git clone https://github.com/limine-bootloader/limine.git --branch=v5.x-branch-binary --depth=1

    - name: Build the Limine Bootloader
      run: make -C limine

    - name: Build The Operating System itself
      run: cd source && make -j4 clean && cd ../ && make -j4 -C source && make -j4

    - name: Create coverage for the execution of the Operating System
      run: |
        curl -Os https://uploader.codecov.io/v0.1.0_4653/linux/codecov
        chmod +x codecov
        ./codecov -t ${{ secrets.CODECOV_TOKEN }}

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
