name: Frosted Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: FrostWing
    steps:
    - uses: actions/checkout@v1
    - name: Update packages
      run: sudo apt update

    - name: Install other dependencies
      run: sudo apt install -y make bison flex texinfo nasm mtools wget tar binutils build-essential
    
    - name: Build Doxygen Documentations
      run: doxygen

    - name: Build The Operating System itself
      run: ./test.sh

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
